### ISSUE TITLE
[Question] - Test framework

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [rogeralsing/Wire#101]
I see that MSTest is the test framework. This framework is really out of date in comparison to its competitors in many ways. What do you think about NUnit or XUnit? Asking because I have some plans to increase code coverage

**Comment by rogeralsing** [comment]
I think xUnit is the way to go and that has support for .NET core too, (maybe nUnit does too?)
The only reason why MSTest was used is that I've had problems with the VS testrunner for xUnit from time to time.

**Comment by lukasz-pyrzyk** [comment]
As far as I know, NUnit has also support for .NET Core.  Still, guys from MS are using xUnit as a default test framework for .NET Core projects.

I would prefer XUnit because I like the the concept of test framework without teardown, setup etc.
If you agree, we can close this issue, I will handle PR

**Comment by Aaronontheweb** [comment]
@lukasz-pyrzyk do it (XUnit)

**Comment by rogeralsing** [comment]
XUnit support have been merged. closing
