### ISSUE TITLE
Description of what Wire can/can't do

### ISSUE THREAD

**Issue by Horusiath** [rogeralsing/Wire#105]
I think, serializer description should clearly state about the its possibilities and conditions. Something like FAQ would be great. Example questions:
- Is Wire able to retain objects references?
- Does it need some type annotations or other compile-time mechanics?
- Is it able to serialize/deserialize custom generic types?
- Is it able to serialize/deserialize internal or private types?
- Is it able to serialize/deserialize private fields or properties with private getter?
- Is it able to use type constructors on deserialization? If so:
  - Can those constructors be internal/private?
  - In case of multiple constructors for target type, how will it resolve correct constructor?
- Is it able to serialize/deserialize delegates? What about anonymous lambdas?
- Is it able to serialize C# LINQ expressions?

**Comment by rogeralsing** [comment]
Quick answers if anyone wonders:
- Is Wire able to retain objects references?
  **Yes**
- Does it need some type annotations or other compile-time mechanics?
  **No**
- Is it able to serialize/deserialize custom generic types?
  **Yes**
- Is it able to serialize/deserialize internal or private types?
  **Yes**
- Is it able to serialize/deserialize private fields or properties with private getter?
  **Yes** 
- Is it able to use type constructors on deserialization? If so:
  **No**
  Not planned.
- Is it able to serialize/deserialize delegates? 
  **Yes**
- What about anonymous lambdas?
  **Yes**
- Is it able to serialize C# LINQ expressions?
  **Don't know**
  I see no reason why it shouldn't, but haven't tried myself

I will try to clean this up and add to the readme file

**Comment by Horusiath** [comment]
Regarding last one - I've created a [bunch of tests](https://github.com/Horusiath/Wire/blob/expression-serialization/Wire.Tests/ExpressionTests.cs) to check if it's possible to serialize some of the C# LINQ expression variants (not all of them are there yet). Most of them are failing right now.

I think, that quite common problem is serialization of reflection data - Wire supports MethodInfo serialization, but I can see, that ConstructorInfo, PropertyInfo and FieldInfo are not supported.

Second issue concerns _System.Reflection.AmbiguousMatchException: Ambiguous match found._ that occurs [here](https://github.com/akkadotnet/Wire/blob/dev/Wire/SerializerFactories/EnumerableSerializerFactory.cs#L18).

---

EDIT: it turned out that `typeof(Expression).GetTypeInfo().GetMethod("Add")` will throw an error. I'm going to send patch for this one.
