### ISSUE TITLE
No support for struct with a non-default constructor?

### ISSUE THREAD

**Issue by ShamsulAmry** [rogeralsing/Wire#124]
I stumbled across an error when serializing a struct across Akka nodes.
Managed to isolate the issue when having Wire serializer a struct with non-default constructor.

**Comment by rogeralsing** [comment]
This is probably a code gen bug, will look Into it

**Comment by ShamsulAmry** [comment]
Thanks

**Comment by ShamsulAmry** [comment]
My bad, actually the error happened because Wire can't deserialize the properties without setters.

I was actually testing this, which can be deserialized without error:

```
public class ClassWithNonDefaultCtor
{
    public ClassWithNonDefaultCtor(string prop1, int prop2)
    {
        Prop1 = prop1;
        Prop2 = prop2;
    }

    public string Prop1 { get; }
    public int Prop2 { get; }
}
```

Then tried changing it to struct, which failed:

```
public class StructValueWithNonDefaultCtor
{
    public StructValueWithNonDefaultCtor(string prop1, int prop2)
    {
        Prop1 = prop1;
        Prop2 = prop2;
    }

    public string Prop1 { get; }
    public int Prop2 { get; }
}
```

**Comment by mellinoe** [comment]
I'm seeing this as well, assuming you meant for your second example to be

``` CSharp
public struct StructValueWithNonDefaultCtor
{
    ...
}
```

I also have some structures with public readonly fields, rather than readonly properties.

**Comment by ShamsulAmry** [comment]
@mellinoe, thanks for the correction. Wrongly copy-paste-edited. 

I think it make sense for the deserializer to fail since it can't write to read-only fields and properties.

**Comment by ShamsulAmry** [comment]
@rogeralsing, I'm still looking to make NodaTime workable across Akka nodes. However, due to the issue above, NodaTime won't naturally serialize on its own and I'm thinking of using Wire's surrogate feature to make it happen. But I'm not sure how to do that with Akka-Wire implementation. Any hint?

**Comment by ia64mail** [comment]
@rogeralsing Hi! Do you have any updated regarding this issue? I run into the same problem when serializing a structure with non-default constructor. This ticket has been closed a month ago but final resolution is unknown.

**Comment by Horusiath** [comment]
@ia64mail AFAIK this issue remains unresolved on Wire, but it has been fixed on Hyperion (akka.net fork of Wire) as of https://github.com/akkadotnet/Hyperion/pull/9
