### ISSUE TITLE
Wire performance improvements

### ISSUE THREAD

**Issue by Scooletz** [rogeralsing/Wire#129]
This issue aims at starting a discussion about Wire performance. The main reason for it are the benchmarks of [ZeroFormatter](https://github.com/neuecc/ZeroFormatter) and some building blocks of `protobuf-net` reading streams in big chunks to a helper array.

### Introduction
Currently wire operates on the level of a stream abstraction. That prohibits a direct access to the `byte[]` of a stream if any, requiring some coping to a helper buffers. We did a good job in limiting the needs of obtaining this helper buffer, but still, the serializer works on the stream level.
**ZeroFormatter** work on the `byte[] + offset` level, which makes it much faster and robust as it can make the buffer `fixed` and work with `byte*`.
**Protobuf-net** prefetches a chunk of memory to a helper `byte[]`, which effectively moves it to the ZeroFormatter zone.

### Current state
After reviewing the current structure, in my opinion, the coupling to the stream abstraction is very big. I can't see a way of peaceful moving to a better performing code without a lot of changes breaking the `ValueSerializer` API. Fortunately, it's not the user lvl API and even if changed, it's highly probable that after these breaking changes, users' code would just work.

### Considerations
After reviewing two abstraction classes: `SessionAwareByteArrayRequiringValueSerializer<TElementType>` and `SessionIgnorantValueSerializer<TElementType>` I can see, that the only reason for separating them was the usage of the session. In every other case, they serialize values of a fixed length. If I was thinking of an abstraction being closer to the metal (`byte[]` or `byte*`). I'd say that any class that derives from one of them could be written as something like the following example:

```
public sealed class NewByteSerializer : ConstLengthValueSerializer<byte>
{
    public const byte Manifest = 4;

    public unsafe NewByteSerializer() : base(Manifest, () => Write, () => Read)
    { }

    static unsafe byte Read(byte* buffer)
    {
        return *buffer;
    }

    static unsafe void Write(byte* buffer, byte value)
    {
        *buffer = value;
    }

    public override int Size { get; } = sizeof(byte);
} 
```

Which instead of working with stream and sessions, would just operate on the byte level. It could be moved one step further by replacing `Write` & `Read` with `EmitWrite` & `EmitRead` that would emit the writer/reader directly to the higher lvl serializer.
With this shape the emitting get more complex as:
- the advancement of the `buffer` when reading/writing needs to be controlled
- when writing, the buffer must be checked for the overflow
- pinning with `fixed` must be emitted

If we decided to work on the `byte[]` level, this would remove the pinning points, still, leaving the buffer management for writes and the buffer advancement. The `ICompiler` would require a lot of work.

The redesign of the library in this shape would be hard (it looks that much more needs to be pushed down, to custom serializers) but could bring a big boost of performance.

**Comment by Scooletz** [comment]
Looking forward to hearing from you @rogeralsing :-)

**Comment by jogibear9988** [comment]
Would the new Span<T> help out with your Problems?

**Comment by Scooletz** [comment]
Possibly yes @jogibear9988 . I won't be able to work on this, so if you're willing to make this change, it's all yours.
