### ISSUE TITLE
CollectionTests.CanSerializeDictionaryKeysAndValuesByteChar is failing

### ISSUE THREAD

**Issue by Horusiath** [rogeralsing/Wire#131]
One of the unit tests `CollectionTests.CanSerializeDictionaryKeysAndValuesByteChar` is constantly failing. A value of the { 0, 'z' } entry upon deserialization is '\0'. It's on .NET 4.5 and as far as I've checked it falls inside il compiler for chars.

**Comment by rogeralsing** [comment]
Fixed
