### ISSUE TITLE
Wire 0.8.2 is not compatible with 0.8.1

### ISSUE THREAD

**Issue by Danthar** [rogeralsing/Wire#134]
It fails when deserialising datetime or datetimeoffset types

Not sure if this is a bug, or an intentional change.

**Comment by rogeralsing** [comment]
Are you certain that the version used to generate the previous payload was 0.8.1?
there was an introduction of serializing the `DateTime.Kind` and `DateTimeOffset.Kind` properties in a much earlier version.
[edit]
That change was introduced in 0.7.0
Which would be my first bet. as the payload for those types increased with one byte.

Ore those part of a bigger message?
Anything with exotic collections?

Important to know here is that version tolerance is not yet implemented.

**Comment by rogeralsing** [comment]
Related to #33

**Comment by Danthar** [comment]
Its part of a much bigger message. The message does has one collection. But thats a standard .net list<T>.
I realize there is no hard backwards compat guarentee anywhere. But i guess that it stemmed from the fact that its not mentioned anywhere. Combined with the fact that some previous releases had been (afaik) (seemingly) backwards compatible.

Some small release notes when you publish a new version here in the github repo would help in creating awareness. Or it could just be me ;)

But im sure it was serialized with 0.8.1 . After i downgraded the deserializing side to 0.8.1 it started working.

I since moved both sides to 0.8.2.

**Comment by rogeralsing** [comment]
There are no changes in schema or functionality between 0.8.1 and 0.8.2, it's a patch for the hash set serialization performance.

If you are able to replicate it, please let me know.
Because if there is schema breakage between the two versions, that's likely a bug.

The versioning strategies of Wire are described here:
https://github.com/rogeralsing/Wire#version-tolerance

Nr 3) there should be expanded on as this is the part that is not implemented.

**Comment by Danthar** [comment]
Ill check about reproducing it. Ill get back to you on that next monday

**Comment by Danthar** [comment]
I cant seem to reproduce it. So it seems there are some other issues involved that i've missed. Im suspecting some internal-project old-build shenanigans that i probably solved with a hard rebuild all.

Closing this issue
