### ISSUE TITLE
Can't convert RemoteActorRef to ISurrogate

### ISSUE THREAD

**Issue by fjoppe** [rogeralsing/Wire#16]
Hi,

I am using Akka.Net in combination with Akkling (0.2.1). I have finally established a connection between two remote actor-systems. From the actor system which has the task of a state server, I want to send an IActorRef to the client (who is asking for this). The type is: Akkling.ActorRefs.IActorRef<'MySharedDU>

This results in the following exception at the client side:

> [ERROR][26-12-2015 14:13:42][Thread 0011][[akka://ThisIsMyClient/system/endpointManager/reliableEndpointWriter-akka.tcp%3a%2f%2fThisIsMyServer%40localhost%3a8080-1/endpointWriter]] AssociationError [akka.tcp://ThisIsMyClient@localhost:8090] -> akka.tcp://ThisIsMyServer@localhost:8080: Error [Cannot convert object of type Akka.Remote.RemoteActorRef into the type Akka.Util.ISurrogate.] [   at lambda_method(Closure , Object , Object )
>   at Wire.CodeGenerator.<>c__DisplayClass4_0.<GenerateFieldInfoDeserializer>b__1(Stream stream, Object o, DeserializerSession session)
>   at Wire.CodeGenerator.<>c__DisplayClass1_0.<MakeReader>b__0(Stream stream, DeserializerSession session)
>   at Wire.ValueSerializers.ObjectSerializer.ReadValue(Stream stream, DeserializerSession session)
>   at Wire.ValueSerializers.FromSurrogateSerializer.ReadValue(Stream stream, DeserializerSession session)
>   at Wire.Serializer.Deserialize(Stream stream)
>   at Akkling.Serialization.WireSerializer.FromBinary(Byte[] bytes, Type _arg1) in D:\projects\dev\Akkling\src\Akkling\Serialization.fs:regel 33
>   at Akka.Remote.MessageSerializer.Deserialize(ActorSystem system, SerializedMessage messageProtocol)
>   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, SerializedMessage message, IActorRef senderOption)
>   at Akka.Remote.EndpointReader.OnReceive(Object message)
>   at Akka.Actor.UntypedActor.Receive(Object message)
>   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
> Cause: Unknown

I think the issue is in Wired? I just upgraded to Wired v0.0.6 (Akkling was stil dependent on v0.0.1 which gave even bigger issues). Note, I translated the exception manually from my own language, so there can be textual mismatches with the official english version.

**Comment by fjoppe** [comment]
I have been playing around a bit, and I discovered that my code had a type mismatch. The above stacktrace origins from that type mismatch, between fsi client, and remote system. The Remote was sending something different than the fsi client was expecting.

However I corrected this type mismatch, and I still got the same stacktrace. So I did a little bit more digging. 

The `IActorRef` for which the above stacktrace is produced, originates from `Akkling.ActorRefs`. Actor refs from that namespace have a `toSurrogate` function. So that's a clue.

The namspace also has functions `Akkling.ActorRefs.typed` and `Akkling.ActorRefs.untyped`, which appear to convert strong type ActorRefs from the Akkling namspace, to the ActorRefs from `Akka.Actors` namespace.

And what do you know? Actor refs of type `Akka.Actors.IActorRef` càn be send over the wire, and it does not give the exception above. It minimally looks good.

So this may be one where @horusiath perhaps could be interested in, because I'm not sure at which side this issue lies.

**Comment by Horusiath** [comment]
@fjoppe Could you make it reproducible on some code example, that can be shared?

**Comment by fjoppe** [comment]
@horusiath, it's on Github now. 

This code still has the issue. [This was the client (line 48)](https://github.com/fjoppe/ThreeIsACrowdActorBased/blob/25bf874002c5e66e5bd8028b189b4ba18a832b70/GameEngine.FSharp/CallRemoteActor.fsx). [This was the remote side (line 260)](https://github.com/fjoppe/ThreeIsACrowdActorBased/blob/25bf874002c5e66e5bd8028b189b4ba18a832b70/GameEngine.FSharp/Orchestrator.fs).

I have corrected this, and the Akkling actorrefs are now converted to untyped. 

The client in the [fsi now looks like this (line 49)](https://github.com/fjoppe/ThreeIsACrowdActorBased/blob/master/GameEngine.FSharp/CallRemoteActor.fsx). The remote system running as a service [now looks like this (line 317)](https://github.com/fjoppe/ThreeIsACrowdActorBased/blob/master/GameEngine.FSharp/Orchestrator.fs).

**Comment by rogeralsing** [comment]
Can this be closed, was the issue related to how Akkling converts between typed and untyped ActorRefs?

cc @Horusiath

**Comment by fjoppe** [comment]
I don't know on which side this issue is. I worked around it, but one may want to solve it the proper way. I can close it if you want.

**Comment by Horusiath** [comment]
The issue may be on the Akkling side. I'll take a closer look on this this Sunday.
