### ISSUE TITLE
String length serialization bug

### ISSUE THREAD

**Issue by TechInterMezzo** [rogeralsing/Wire#21]
There is a bug in the string serialization code. For strings longer than 254 bytes you write a marker with a value of 254. Shouldn't it be 255? Also you add 1 to the length before writing it to the stream and subtract 1 after reading the length from the stream ([source](https://github.com/rogeralsing/Wire/blob/94c4975c1e48d03ffbcfb70edd881385d58e1e89/Wire/ValueSerializers/StringSerializer.cs#L34)). I don't know why you did this in the first place, but this also collides with the marker and produces some bugs for me.

**Comment by rogeralsing** [comment]
You are correct.
I have fixed this in the dotnet core dev branch:

https://github.com/rogeralsing/Wire/blob/dotnetcore/Wire/ValueSerializers/StringSerializer.cs

Regarding the +1 -1 length.

```
0 = null
1 = 0 length
2 = 1 length 
etc..
255 = marker for long string
```

I have a test that verifies length per length

``` csharp
            for (int i = 0; i < 2000; i++)
            {
                var str = new string('a',i);
                SerializeAndAssert(str);
            }
```

The updated code now passes this test.

**Comment by TechInterMezzo** [comment]
Thank you for the fix and explanation. Your serializer is really useful for my simple ipc library.
