### ISSUE TITLE
Improve exception message when type cannot be loaded on deserialization

### ISSUE THREAD

**Issue by ZoolWay** [rogeralsing/Wire#25]
By mistake I recently tried to deserialize a type which was unknown. The deserializer throws an exception because it could not load the `ForeignAssembly 1.0.0.0 or one of its dependencies`. It would be very good to known in the cases when a type cannot be loaded/created, which type that has been. Switching back to the JSON serializer I got an exception message containing the name (and assembly) of the type trying to deserialize. That is very helpful and Wire should do the same.

**Comment by rogeralsing** [comment]
I'm on it
