### ISSUE TITLE
Version tolerance rquirements

### ISSUE THREAD

**Issue by rogeralsing** [rogeralsing/Wire#33]
The current plan for version tolerance is to support added and removed fields.
If there is a type missing, there is nothing to generate the reader from, and thus we cannot support this today.

User feedback is welcome

**Comment by veblush** [comment]
How about writing type manifests into `versionTolerantHeader` to support type changes. It could be quite often to change integer types such as `int` to `long`, etc.

**Comment by rogeralsing** [comment]
@veblush that is a great idea.
I would like to make this configurable to allow users to opt in/out of less/more tolerance.
Also related to #66

**Comment by rogeralsing** [comment]
I would like to add an identifier to the ValueSerializerFactories too, so that this ID is emitted together with the typename/id. allowing version tolerant readers to read streams where even types have been removed
