### ISSUE TITLE
Shorten type manifest

### ISSUE THREAD

**Issue by rogeralsing** [rogeralsing/Wire#34]
Currently, the type manifest for custom types consist of the assembly qualified type name.
This could be shortened by spitting typename and assembly name.
instead of `foo.bar.baz, my.asm` we could write the two separately, and introduce an assembly lookup much like the current type id lookup we have.
that way, only the first occurance of an assembly would be emitted, all others would emit an assembly ID.
This would likely speed up both lookup time and reduce payload size.

**Comment by verysimplenick** [comment]
Yep, maybe can not save assembly name at all? 
Currently I use dynamic generated assemblies if I use Wire for save some generated object I has in file something like this:

```
System.Collections.Generic.List`1[[MyNameSpace.GeneratedType, Generated_26ebf0d0-c293-4fdd-9ff2-3adcd92a68af, Version=0.0.0.0]]
```

Wire is fastest serializer that I bench (msgpack same at write, but reading in Wire is faster), but wire serialize type info, maybe can configure this?
