### ISSUE TITLE
Support Full AOT (Ahead of Time compilation).

### ISSUE THREAD

**Issue by veblush** [rogeralsing/Wire#38]
In full [AOT](http://www.mono-project.com/docs/advanced/runtime/docs/aot/) environment like iOS, runtime jitting is not allowed, which means no runtime code generation at all.
For example, it's impossible to emit code and use a generic type which parameter types are not determined at compile time.

To support this, we need to put workaround code for every dynamic code. For example, `CodeGenerator.GenerateWriteAllFieldsDelegate` can be changed like:

``` csharp
private static ValueWriter GenerateWriteAllFieldsDelegate(
    List<ValueWriter> fieldWriters)
{
    if (fieldWriters == null)
        throw new ArgumentNullException(nameof(fieldWriters));

    if (use_dynamic_code) // CHECK SERIALIZER OPTION TO USE DYNAMIC CODE
    {
        // fast but not working code on AOT.
        var streamParam = Parameter(typeof (Stream));
        var objectParam = Parameter(typeof (object));
        var sessionParam = Parameter(typeof (SerializerSession));
        var xs = fieldWriters
            .Select(Constant)
            .Select(
                fieldWriterExpression =>
                    Invoke(fieldWriterExpression, streamParam, objectParam, sessionParam))
            .ToList();
        var body = Block(xs);
        var writeallFields =
            Lambda<ValueWriter>(body, streamParam, objectParam,
                sessionParam)
                .Compile();
        return writeallFields;
    }
    else
    {
        // slow but working code on AOT.
        return (stream, obj, session) => fieldWriters.ForEach(w => w(stream, obj, session));
    }
}
```

How about this?

**Comment by rogeralsing** [comment]
Asked on Gitter but Ill add it here too.
How does the AOT path work? it will end up using reflection with FieldInfo.Get/SetValue or how does that work?

**Comment by veblush** [comment]
Yes. It usually ends up with a bunch of Get/SetValue that is safe on AOT environment. And it's also possible to use generic types or methods which can be instantiated in compile-time.

**Comment by rogeralsing** [comment]
I will close this one as it is out of scope
