### ISSUE TITLE
Add strong schema support

### ISSUE THREAD

**Issue by rogeralsing** [rogeralsing/Wire#66]
Protobuf and MS Bond have a better version tolerance story as they use ID tagging on properties.
I'm thinking about doing the same for Wire.

e.g.

``` csharp
[WireType(0)]
public class MyMessage
{
    [WireField(0)]
    public string SomeProperty {get;set;}

    [WireField(1)] 
    public int SomeOtherProperty {get;set;}
}
```

Thoughts about this?

**Comment by Horusiath** [comment]
In case if this is still a matter - I'd say, that the better option would be to add something like mapping class i.e.:

```csharp
class MyMessageSchema : WireSchema<MyMessage>
{
    public MyMessageSchema()
    {
        TypeId(0);
        Field(0, m => m.SomeProperty);
        Field(1, m => m.SomeOtherProperty);
    }
}
```

Why this way? Having a mapping class effectively splits a data, contract and its implementation. This means that you can create a schema for messages defined in assemblies, you don't have an access to or where you don't want to introduce a Wire as a dependency.

**Comment by rogeralsing** [comment]
Closing as out of scope for now, might reopen later
