### ISSUE TITLE
Add SERBENCH test harness for Wire

### ISSUE THREAD

**Issue by itadapter** [rogeralsing/Wire#73]
Add, serializer benchmark support for  
https://github.com/aumcode/serbench so Wire can be compared to protobuf and dozen others
including NFX.Slim which is used for BigMemory.

This is actually an FYI, ill post results here

@leo-gan @vlapchenko

**Comment by rogeralsing** [comment]
Awesome, it would be nice to see it implemented with different options too, pretegister types, preserveObjectReferences etc.

**Comment by itadapter** [comment]
Roger, could you please provide values for the following fields (I took Slim as example). I need it for metadata:

```
[SerializerInfo( 
     Family = SerializerFamily.Binary,    
     MetadataRequirement = MetadataRequirement.None,
     VendorName = "IT Adapter LLC",
     VendorLicense = "Apache 2.0 + Commercial",
     VendorURL = "http://itadapter.com",
     VendorPackageAddress = "http://github.com/aumcode/nfx",
     FormatName = "Slim",
     LinesOfCodeK = 7,    
     DataTypes = 32,
     Assemblies = 1,
     ExternalReferences = 0,
     PackageSizeKb = 1500
)]
```

**Comment by itadapter** [comment]
Yes, we will add the options as test properties, so would be able to run test script like so:

```
 test{ name="with obj refs" obj-ref=true....}
 test{ name="no obj refs" obj-ref=false....}
Ill come around with questions how to do it properly in Wire.
Also SERBENCH does support "Known types" injection so that is going to be covered as well
```

**Comment by itadapter** [comment]
@rogeralsing 
 Take a look at this: 1 root object is stellar, a list[100] something is different.
I suspect that you use pre-allocated buffer maybe? Notice that Protobuf has the same problem.
However on 500 protobuf recovers, but Wire doesnt.  I need to get answers about ref tracking I sent you an email with questions.
![20160819_wire](https://cloud.githubusercontent.com/assets/2273574/17827539/6863d9ce-664c-11e6-810f-309712eba4d6.png)

**Comment by rogeralsing** [comment]
[SerializerInfo( 
     Family = SerializerFamily.Binary,  
     MetadataRequirement = MetadataRequirement.None,
     VendorName = "Akka.NET Team",
     VendorLicense = "Apache 2.0",
     VendorURL = "http://getakka.net",
     VendorPackageAddress = "http://github.com/akkadotnet/wire",
     FormatName = "Wire",
     //I need to check the rest, don't know on top of my head 
)]

**Comment by rogeralsing** [comment]
Also, please use the latest 0.8.0 package
https://www.nuget.org/packages/Wire/0.8.0

There should be some significant improvements if you havent compiled from sources here

**Comment by itadapter** [comment]
I have added a fix to Wire.PerfTests for SlimSerializer (pull req sent). Updated SERBENCH to 0.8.0
