### ISSUE TITLE
Deserialize surrogates

### ISSUE THREAD

**Issue by charleslee89** [rogeralsing/Wire#75]
I meet a problem when deserialize a list of surrogate objects if some of them refer the same object.

Say, I have serialized  List<Original>(){ original_1, original_1 }

Mechanism of deserialization:
For the 1st item:
Deserializes surrogate_1.
Adds surrogate_1 into DeserializerSession._objectById.
FromSurrogateSerializer translates the surrogate_1 into original_1.

For the 2nd item:
Deserializes surrogate_1 again. Indeed it is a reference of surrogate1 ,hence returns result of DeserializerSession.GetDeserializedObject , which is surrogate_1.
But there, it is supposed to be  an object of Orginal type.

Did I do anything wrong?

**Comment by rogeralsing** [comment]
I didn't quite get what the actual problem is.
Is it that the two objects does not result in the same instance?

**Comment by charleslee89** [comment]
It causes System.InvalidCastException;

In the process of deserializing  List<Original>, after the first surrogate object has been deserialized , the second one ( refer to the same instance ) is returned without translation, which is a surrogate instance.

**Comment by rogeralsing** [comment]
Could you provide a PR with a failing unittest for this? it would make my investigation a lot smoother.

**Comment by charleslee89** [comment]
`

```
   [Fact]
    public void can_deserialize_surrogates_which_refer_the_same_instance()
    {
        var surrogateHasBeenInvoked = false;
        var surrogates = new[]
        {
            Surrogate.Create<Foo, FooSurrogate>(FooSurrogate.FromFoo, surrogate =>
            {
                surrogateHasBeenInvoked = true;
                return surrogate.Restore();
            })
        };
        var stream = new MemoryStream();
        var serializer = new Serializer( new SerializerOptions(surrogates: surrogates, preserveObjectReferences:true));

        var foo = new Foo { Bar = "I will be replaced!"}; 
        var fooArray = new Foo[] { foo, foo }; 

        serializer.Serialize(fooArray, stream);  

        var bytes = stream.ToArray();
        Foo[] actualArray;
        using (var ms = new MemoryStream(bytes))
        { 
            var ret = serializer.Deserialize<object>(ms);
            actualArray = (Foo[])ret;
        }

        Assert.Equal(actualArray[0], actualArray[1]);
        Assert.True(surrogateHasBeenInvoked);
    }
```

In short, Foo & FooSurrogate are coplied from SurrogateTest.cs in Wire.Test project and overrode the Equals functions. In this case, calling serialize.Desrialize  throws System.InvalidCastException: cannot cast FooSurrogate to Foo.

The similiar case happens when deserializing Akka.Persistence.AtLeastOnceDeliverySnapshot , which contains the same ActorPath. 

It is probably because DeserializerSession._objectById refers the surrogate instance.
