### ISSUE TITLE
NetSerializer LargeStruct test perf

### ISSUE THREAD

**Issue by rogeralsing** [rogeralsing/Wire#88]
cc @Scooletz 

When serializing the "LargeStruct" from NetSerializer test suite, Wire performs considerably worse than NetSerializer, about twice as slow.

I see no obvious reason why we do so as our IL generated writer for the struct should be just as slim as the one in NetSerializer.

cc @tomba
Are there any specific tricks NetSerializer uses in terms of structs?

Our generated Serializer for the struct would look pretty much like this

``` csharp
public virtual void Serialize(Stream stream, object value, SerializerSession session)
{
        var x = (LargeStruct)value;
        var buffer = session.GetBuffer(8); //pre allocated
        NoAllocBitConverter.GetBytes(x.field1,buffer);
        Stream.Write(buffer,0,8);
        NoAllocBitConverter.GetBytes(x.field2,buffer);
        Stream.Write(buffer,0,8);
        NoAllocBitConverter.GetBytes(x.field3,buffer);
        Stream.Write(buffer,0,8);
        NoAllocBitConverter.GetBytes(x.field4,buffer);
        Stream.Write(buffer,0,8);
}
```

We do have a virtual call and boxing of the struct ATM. but can that really make up for as much as twice much overhead?

I've tried using NetSerializer VarInts for ulong too, but no positive performance change.

**Comment by rogeralsing** [comment]
Twice as slow might have been over exaggerated, 1.5 times slower is more correct.
400 ms vs 600 ms.

Changing it to a class brings it down to 550, but still significantly slower than NetSerializer.
also, it is only the serialize step that is slower, deserialize is actually faster.

**Comment by Scooletz** [comment]
Nice finding. Will take a look at it.
Just to be specific: 
- there are 4 virtual calls
- bit converter calll should look like `NoAllocBitConverter.GetBytes(x.field1,buffer)`

**Comment by rogeralsing** [comment]
4?
The primitives are inlined into the ICompiler pipeline arnt they? EmitWrite.
That leaves just the outer function to write the entire struct, or am I missing something now?

**Comment by Scooletz** [comment]
4 calls to `Stream.Write` which is `virtual`.

**Comment by tomba** [comment]
> Are there any specific tricks NetSerializer uses in terms of structs?

No, I don't think so (well, there's "direct serialization", but that's not relevant here).

You can actually make NetSerializer emit an assembly dll file containing all the generated code, by doing a debug build and uncommenting the "GenerateDebugAssembly" line in Test/Tester.cs. That assembly can't be used as such, but you can dissassemble it, which I've found a great way to understand issues.

**Comment by rogeralsing** [comment]
Ok, I found the issue, we lacked handling for valuetypes when creating new objects so it fell back onto the FormattingServices.GetEmptyObject.

Still slower than NetSerializer here but I'd say that is expected as we carry more state around.

**Comment by rogeralsing** [comment]
I've got it down to only differ with some 50ms. 
I realized that we do not need to lookup known types while serializing to determine if we need to write manifest or not.
We can simply create an object serializer that never writes the manifest if the type is known when the serializer is generated and register that into our serializer lookup.
This made known type serialization a lot faster.

**Comment by rogeralsing** [comment]
Closing this one, the perf is good enough in the current code
